CODEOWNERS
This should in the future require one of us or additionally added members to review code before it can be merged into master for this repository.
=> Created CODEOWNERS

CODEOWNERS, chatbot/chat.py, requirements.txt
=> Boilerplate

CODEOWNERS, README.md, chatbot/chat.py, chatbot/commands.py
* functions moved to command.py
* dictionary created for function storage (because I wanted to try doing this, not because it's necessarily a great idea)
* basic help functionality introduced
* can no longer reply to itself
=> all functions in a dictionary in command.py

chatbot/botconfig.py, chatbot/chat.py
Addresses #10 and #16.
Simple config file setup. Configurable variables:
- `username`
- `client_url` matrix server
- `command_prefix` the symbol preceding commands. currently $.
- `rooms` - list of rooms the bot will connect to.
=> Separate config file and multi-room support

README.md
=> fixed incorrect file name in README

chatbot/chat.py
=> add ability to be run as a background task

chatbot/listenercenter/listeners/githublistener.py
=> Fixed PR event spam

chatbot/commandcenter/commands/office.py
=> Added ability to list your current registered mac addresses.

chatbot/commandcenter/commands/office.py
=> Added message for an empty cclub room.

chatbot/commandcenter/commands/MCOnline.py
Just gives number of people online
=> MCOnline Command

chatbot/commandcenter/commands/floor.py
=> Very important command

chatbot/commandcenter/commands/yalldve.py
Now there is a few more slang pieces to use and a tiny chance of infinite slang
=> Enhanced $yalldve

chatbot/commandcenter/commands/led.py
```
$led <color> [type]
$led #ffffff -- changes the color of the lights to white (doesn't change mode)
$led #ff0000 color -- changes the color of the lights to red and changes mode to 'color'
$led #00ff00 chase -- changes the color of the lights to green and changes mode to 'chase'
$led #0000ff rainbow -- changes the color of the lights to blue and changes mode to 'rainbow' (which nullifies the color selection)
$led #000000 random -- changes the color of the lights to off and changes mode to 'random' (randomly picked colors and modes)
```
=> Add command to change the colors of the LEDs in the office

chatbot/chat.py, chatbot/commandcenter/commands/img.py, chatbot/commandcenter/commands/img_api_key.py
searches for "img_0000" etc on youtube. who knows what you'll get!
```
spacedog: $img (random video)
ccawmu: IMG_0892.flv, Bé Ngọc Quận 7.: https://youtube.com/watch/1EiRl6j12M4
spacedog: $img 2222 (specific number)
ccawmu: IMG_2222, IMG_2222.: https://youtube.com/watch/CkiqOv5p8TM
```
=> $img command

chatbot/commandcenter/commands/brainfuck.py
Pass input to brainfuck like `$brainfuck ,[.,] this text will be echoed and the code treats the end like reading 0x00`
=> Support input in brainfuck

chatbot/commandcenter/commands/wordle.py
it does what it says on the box
=> wordle: better layout, no geeks, room-independent games, reject duplicates

chatbot/chat.py
Reverts ccowmu/ccawmunity#82 which caused the bot to break upon sent commands
=> Revert "Fix command string parsing, cleanup"

chatbot/chat.py
* Change message body formatting to only preserve whitespace within quotes
* Organize imports
* Remove trailing whitespace
=> Fix command string parsing, cleanup

chatbot/commandcenter/commands/randdong.py
Created $randdong to print an ASCII dong of random length - e.g., 8===D for length 3.
Uses a log-normal distribution to choose length, so as to favor shorter dongs, while allowing for potentially very long dongs, with decreasing probability as lengths increase beyond around 10
=> created randdong command

chatbot/commandcenter/commands/wordle.py
=> Fix alias support for wordle.py

chatbot/commandcenter/commands/knockers.py
added kockers file to return random set of titties
=> kockers bot command

chatbot/static/welcome-message.txt
Added small section regarding rules and the enforcement of said rules.
=> Added section about moderation

chatbot/commandcenter/commands/course_lookup.py, chatbot/commandcenter/commands/wordle.py, chatbot/requirements.txt
Implemented Course Lookup Command
=> Course Lookup Command

chatbot/commandcenter/commands/wordle.py
=> Fixed wordle

chatbot/commandcenter/commands/topic.py
changed old president and vice president to new president and vice president.
=> update permissions topic.py
